{"name":"ALG_100_DF","ppdf:dataflowId":"cafe8846-e1a8-4c2b-8750-329424f60877","ppdf:owner":{"tenantId":"af0e94e8-6639-488e-a9b8-1c73d089ba55","userId":"0d52a35b-4796-4823-9cf7-9bc12ed33881"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2024-02-29T09:43:18.5065472+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"activityevents":{"queryId":"b2fe5051-4d49-48c0-8ce9-a1bd1018f308","queryName":"activityevents","loadEnabled":true},"activityevents_DataDestination":{"queryId":"9c567860-8ed0-477d-ba10-8456e5bc1ff8","queryName":"activityevents_DataDestination"},"activityevents_WriteToDataDestination":{"queryId":"de23009e-c39a-4c9c-a227-1d6c4c776844","queryName":"activityevents_WriteToDataDestination"},"activityevents_TransformForWriteToDataDestination":{"queryId":"be30fc2d-9c66-4237-bb07-d00aeb0fe68e","queryName":"activityevents_TransformForWriteToDataDestination"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared activityevents = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"bccb4fda-4fff-4a0b-886e-e7ab5cad3547\"]}[Data]{[lakehouseId = \"eea226c9-28c2-4ab5-827d-52bd3b816b35\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"activityevents\", ItemKind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared activityevents_DataDestination = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"bccb4fda-4fff-4a0b-886e-e7ab5cad3547\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"06498312-87ae-4fcd-b9b8-0e38b1a2af9c\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"activityevents\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[Id = nullable Text.Type, RecordType = nullable Text.Type, CreationTime = nullable DateTime.Type, Operation = nullable Text.Type, OrganizationId = nullable Text.Type, UserType = nullable Text.Type, UserKey = nullable Text.Type, Workload = nullable Text.Type, ResultStatus = nullable Text.Type, UserId = nullable Text.Type, ClientIP = nullable Text.Type, UserAgent = nullable Text.Type, Activity = nullable Text.Type, WorkSpaceName = nullable Text.Type, WorkspaceId = nullable Text.Type, ObjectId = nullable Text.Type, RequestId = nullable Text.Type, ObjectType = nullable Text.Type, ObjectDisplayName = nullable Text.Type, Experience = nullable Text.Type, RefreshEnforcementPolicy = nullable Text.Type, ItemName = nullable Text.Type, CapacityId = nullable Text.Type, CapacityName = nullable Text.Type, DataflowId = nullable Text.Type, DataflowName = nullable Text.Type, IsSuccess = nullable Text.Type, DataflowType = nullable Text.Type, ActivityId = nullable Text.Type, WorkspacesModifiedSince = nullable Text.Type, ExcludePersonalWorkspaces = nullable Text.Type, RequiredWorkspaces = nullable Text.Type, IncludeSubartifacts = nullable Text.Type, IncludeExpressions = nullable Text.Type, Lineage = nullable Text.Type, DatasourceDetails = nullable Text.Type, ExportEventStartDateTimeParameter = nullable Text.Type, ExportEventEndDateTimeParameter = nullable Text.Type, ModelsSnapshots = nullable Text.Type, DatasetName = nullable Text.Type, ReportName = nullable Text.Type, DatasetId = nullable Text.Type, ReportId = nullable Text.Type, ArtifactId = nullable Text.Type, ArtifactName = nullable Text.Type, ReportType = nullable Text.Type, DistributionMethod = nullable Text.Type, ConsumptionMethod = nullable Text.Type, SensitivityLabelId = nullable Text.Type, ArtifactKind = nullable Text.Type, AppName = nullable Text.Type, AppReportId = nullable Text.Type, DatasourceInformations = nullable Text.Type, DatasourceId = nullable Text.Type, GatewayClusterId = nullable Text.Type, IsTenantAdminApi = nullable Text.Type, GatewayClusterDatasources = nullable Text.Type, FolderObjectId = nullable Text.Type, FolderDisplayName = nullable Text.Type, FolderAccessRequests = nullable Text.Type, DashboardName = nullable Text.Type, DashboardId = nullable Text.Type, Datasets = nullable Text.Type, DataConnectivityMode = nullable Text.Type, LastRefreshTime = nullable Text.Type, ImportId = nullable Text.Type, ImportSource = nullable Text.Type, ImportType = nullable Text.Type, ImportDisplayName = nullable Text.Type, SwitchState = nullable Text.Type, PackageId = nullable Text.Type, GatewayId = nullable Text.Type, RefreshType = nullable Text.Type, OldSensitivityLabelId = nullable Text.Type, ActionSource = nullable Text.Type, LabelEventType = nullable Text.Type, ActionSourceDetail = nullable Text.Type, ArtifactType = nullable Text.Type, SensitivityLabelEventData = nullable Text.Type, ItemId = nullable Text.Type, ItemType = nullable Text.Type, CapacityUsers = nullable Text.Type, CapacityState = nullable Text.Type, WorkspacesSemicolonDelimitedList = nullable Text.Type, EndPoint = nullable Text.Type, TileText = nullable Text.Type, GitIntegrationRequest = nullable Text.Type, GatewayClustersObjectIds = nullable Text.Type, GatewayType = nullable Text.Type, GatewayStatus = nullable Text.Type], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared activityevents_WriteToDataDestination = let\r\n  activityevents_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = activityevents_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], activityevents_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  activityevents_WriteToDataDestination;\r\nshared activityevents_TransformForWriteToDataDestination = let\r\n    ColumnMappings = {[SourceColumnName = \"Id\", DestinationColumnName = \"Id\"], [SourceColumnName = \"RecordType\", DestinationColumnName = \"RecordType\"], [SourceColumnName = \"CreationTime\", DestinationColumnName = \"CreationTime\"], [SourceColumnName = \"Operation\", DestinationColumnName = \"Operation\"], [SourceColumnName = \"OrganizationId\", DestinationColumnName = \"OrganizationId\"], [SourceColumnName = \"UserType\", DestinationColumnName = \"UserType\"], [SourceColumnName = \"UserKey\", DestinationColumnName = \"UserKey\"], [SourceColumnName = \"Workload\", DestinationColumnName = \"Workload\"], [SourceColumnName = \"ResultStatus\", DestinationColumnName = \"ResultStatus\"], [SourceColumnName = \"UserId\", DestinationColumnName = \"UserId\"], [SourceColumnName = \"ClientIP\", DestinationColumnName = \"ClientIP\"], [SourceColumnName = \"UserAgent\", DestinationColumnName = \"UserAgent\"], [SourceColumnName = \"Activity\", DestinationColumnName = \"Activity\"], [SourceColumnName = \"WorkSpaceName\", DestinationColumnName = \"WorkSpaceName\"], [SourceColumnName = \"WorkspaceId\", DestinationColumnName = \"WorkspaceId\"], [SourceColumnName = \"ObjectId\", DestinationColumnName = \"ObjectId\"], [SourceColumnName = \"RequestId\", DestinationColumnName = \"RequestId\"], [SourceColumnName = \"ObjectType\", DestinationColumnName = \"ObjectType\"], [SourceColumnName = \"ObjectDisplayName\", DestinationColumnName = \"ObjectDisplayName\"], [SourceColumnName = \"Experience\", DestinationColumnName = \"Experience\"], [SourceColumnName = \"RefreshEnforcementPolicy\", DestinationColumnName = \"RefreshEnforcementPolicy\"], [SourceColumnName = \"ItemName\", DestinationColumnName = \"ItemName\"], [SourceColumnName = \"CapacityId\", DestinationColumnName = \"CapacityId\"], [SourceColumnName = \"CapacityName\", DestinationColumnName = \"CapacityName\"], [SourceColumnName = \"DataflowId\", DestinationColumnName = \"DataflowId\"], [SourceColumnName = \"DataflowName\", DestinationColumnName = \"DataflowName\"], [SourceColumnName = \"IsSuccess\", DestinationColumnName = \"IsSuccess\"], [SourceColumnName = \"DataflowType\", DestinationColumnName = \"DataflowType\"], [SourceColumnName = \"ActivityId\", DestinationColumnName = \"ActivityId\"], [SourceColumnName = \"WorkspacesModifiedSince\", DestinationColumnName = \"WorkspacesModifiedSince\"], [SourceColumnName = \"ExcludePersonalWorkspaces\", DestinationColumnName = \"ExcludePersonalWorkspaces\"], [SourceColumnName = \"RequiredWorkspaces\", DestinationColumnName = \"RequiredWorkspaces\"], [SourceColumnName = \"IncludeSubartifacts\", DestinationColumnName = \"IncludeSubartifacts\"], [SourceColumnName = \"IncludeExpressions\", DestinationColumnName = \"IncludeExpressions\"], [SourceColumnName = \"Lineage\", DestinationColumnName = \"Lineage\"], [SourceColumnName = \"DatasourceDetails\", DestinationColumnName = \"DatasourceDetails\"], [SourceColumnName = \"ExportEventStartDateTimeParameter\", DestinationColumnName = \"ExportEventStartDateTimeParameter\"], [SourceColumnName = \"ExportEventEndDateTimeParameter\", DestinationColumnName = \"ExportEventEndDateTimeParameter\"], [SourceColumnName = \"ModelsSnapshots\", DestinationColumnName = \"ModelsSnapshots\"], [SourceColumnName = \"DatasetName\", DestinationColumnName = \"DatasetName\"], [SourceColumnName = \"ReportName\", DestinationColumnName = \"ReportName\"], [SourceColumnName = \"DatasetId\", DestinationColumnName = \"DatasetId\"], [SourceColumnName = \"ReportId\", DestinationColumnName = \"ReportId\"], [SourceColumnName = \"ArtifactId\", DestinationColumnName = \"ArtifactId\"], [SourceColumnName = \"ArtifactName\", DestinationColumnName = \"ArtifactName\"], [SourceColumnName = \"ReportType\", DestinationColumnName = \"ReportType\"], [SourceColumnName = \"DistributionMethod\", DestinationColumnName = \"DistributionMethod\"], [SourceColumnName = \"ConsumptionMethod\", DestinationColumnName = \"ConsumptionMethod\"], [SourceColumnName = \"SensitivityLabelId\", DestinationColumnName = \"SensitivityLabelId\"], [SourceColumnName = \"ArtifactKind\", DestinationColumnName = \"ArtifactKind\"], [SourceColumnName = \"AppName\", DestinationColumnName = \"AppName\"], [SourceColumnName = \"AppReportId\", DestinationColumnName = \"AppReportId\"], [SourceColumnName = \"DatasourceInformations\", DestinationColumnName = \"DatasourceInformations\"], [SourceColumnName = \"DatasourceId\", DestinationColumnName = \"DatasourceId\"], [SourceColumnName = \"GatewayClusterId\", DestinationColumnName = \"GatewayClusterId\"], [SourceColumnName = \"IsTenantAdminApi\", DestinationColumnName = \"IsTenantAdminApi\"], [SourceColumnName = \"GatewayClusterDatasources\", DestinationColumnName = \"GatewayClusterDatasources\"], [SourceColumnName = \"FolderObjectId\", DestinationColumnName = \"FolderObjectId\"], [SourceColumnName = \"FolderDisplayName\", DestinationColumnName = \"FolderDisplayName\"], [SourceColumnName = \"FolderAccessRequests\", DestinationColumnName = \"FolderAccessRequests\"], [SourceColumnName = \"DashboardName\", DestinationColumnName = \"DashboardName\"], [SourceColumnName = \"DashboardId\", DestinationColumnName = \"DashboardId\"], [SourceColumnName = \"Datasets\", DestinationColumnName = \"Datasets\"], [SourceColumnName = \"DataConnectivityMode\", DestinationColumnName = \"DataConnectivityMode\"], [SourceColumnName = \"LastRefreshTime\", DestinationColumnName = \"LastRefreshTime\"], [SourceColumnName = \"ImportId\", DestinationColumnName = \"ImportId\"], [SourceColumnName = \"ImportSource\", DestinationColumnName = \"ImportSource\"], [SourceColumnName = \"ImportType\", DestinationColumnName = \"ImportType\"], [SourceColumnName = \"ImportDisplayName\", DestinationColumnName = \"ImportDisplayName\"], [SourceColumnName = \"SwitchState\", DestinationColumnName = \"SwitchState\"], [SourceColumnName = \"PackageId\", DestinationColumnName = \"PackageId\"], [SourceColumnName = \"GatewayId\", DestinationColumnName = \"GatewayId\"], [SourceColumnName = \"RefreshType\", DestinationColumnName = \"RefreshType\"], [SourceColumnName = \"OldSensitivityLabelId\", DestinationColumnName = \"OldSensitivityLabelId\"], [SourceColumnName = \"ActionSource\", DestinationColumnName = \"ActionSource\"], [SourceColumnName = \"LabelEventType\", DestinationColumnName = \"LabelEventType\"], [SourceColumnName = \"ActionSourceDetail\", DestinationColumnName = \"ActionSourceDetail\"], [SourceColumnName = \"ArtifactType\", DestinationColumnName = \"ArtifactType\"], [SourceColumnName = \"SensitivityLabelEventData\", DestinationColumnName = \"SensitivityLabelEventData\"], [SourceColumnName = \"ItemId\", DestinationColumnName = \"ItemId\"], [SourceColumnName = \"ItemType\", DestinationColumnName = \"ItemType\"], [SourceColumnName = \"CapacityUsers\", DestinationColumnName = \"CapacityUsers\"], [SourceColumnName = \"CapacityState\", DestinationColumnName = \"CapacityState\"], [SourceColumnName = \"WorkspacesSemicolonDelimitedList\", DestinationColumnName = \"WorkspacesSemicolonDelimitedList\"], [SourceColumnName = \"EndPoint\", DestinationColumnName = \"EndPoint\"], [SourceColumnName = \"TileText\", DestinationColumnName = \"TileText\"], [SourceColumnName = \"GitIntegrationRequest\", DestinationColumnName = \"GitIntegrationRequest\"], [SourceColumnName = \"GatewayClustersObjectIds\", DestinationColumnName = \"GatewayClustersObjectIds\"], [SourceColumnName = \"GatewayType\", DestinationColumnName = \"GatewayType\"], [SourceColumnName = \"GatewayStatus\", DestinationColumnName = \"GatewayStatus\"]},\r\n    SourceColumns = Table.SelectColumns(activityevents, List.Transform(ColumnMappings, each _[SourceColumnName])),\r\n    TargetColumns = Table.RenameColumns(SourceColumns, List.Transform(ColumnMappings, each {_[SourceColumnName], _[DestinationColumnName]}))\r\nin\r\n    TargetColumns;\r\n","connectionOverrides":[{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"activityevents","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"activityevents.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"Id","dataType":"string"},{"name":"RecordType","dataType":"string"},{"name":"CreationTime","dataType":"dateTime"},{"name":"Operation","dataType":"string"},{"name":"OrganizationId","dataType":"string"},{"name":"UserType","dataType":"string"},{"name":"UserKey","dataType":"string"},{"name":"Workload","dataType":"string"},{"name":"ResultStatus","dataType":"string"},{"name":"UserId","dataType":"string"},{"name":"ClientIP","dataType":"string"},{"name":"UserAgent","dataType":"string"},{"name":"Activity","dataType":"string"},{"name":"WorkSpaceName","dataType":"string"},{"name":"WorkspaceId","dataType":"string"},{"name":"ObjectId","dataType":"string"},{"name":"RequestId","dataType":"string"},{"name":"ObjectType","dataType":"string"},{"name":"ObjectDisplayName","dataType":"string"},{"name":"Experience","dataType":"string"},{"name":"RefreshEnforcementPolicy","dataType":"string"},{"name":"ItemName","dataType":"string"},{"name":"CapacityId","dataType":"string"},{"name":"CapacityName","dataType":"string"},{"name":"DataflowId","dataType":"string"},{"name":"DataflowName","dataType":"string"},{"name":"IsSuccess","dataType":"string"},{"name":"DataflowType","dataType":"string"},{"name":"ActivityId","dataType":"string"},{"name":"WorkspacesModifiedSince","dataType":"string"},{"name":"ExcludePersonalWorkspaces","dataType":"string"},{"name":"RequiredWorkspaces","dataType":"string"},{"name":"IncludeSubartifacts","dataType":"string"},{"name":"IncludeExpressions","dataType":"string"},{"name":"Lineage","dataType":"string"},{"name":"DatasourceDetails","dataType":"string"},{"name":"ExportEventStartDateTimeParameter","dataType":"string"},{"name":"ExportEventEndDateTimeParameter","dataType":"string"},{"name":"ModelsSnapshots","dataType":"string"},{"name":"DatasetName","dataType":"string"},{"name":"ReportName","dataType":"string"},{"name":"DatasetId","dataType":"string"},{"name":"ReportId","dataType":"string"},{"name":"ArtifactId","dataType":"string"},{"name":"ArtifactName","dataType":"string"},{"name":"ReportType","dataType":"string"},{"name":"DistributionMethod","dataType":"string"},{"name":"ConsumptionMethod","dataType":"string"},{"name":"SensitivityLabelId","dataType":"string"},{"name":"ArtifactKind","dataType":"string"},{"name":"AppName","dataType":"string"},{"name":"AppReportId","dataType":"string"},{"name":"DatasourceInformations","dataType":"string"},{"name":"DatasourceId","dataType":"string"},{"name":"GatewayClusterId","dataType":"string"},{"name":"IsTenantAdminApi","dataType":"string"},{"name":"GatewayClusterDatasources","dataType":"string"},{"name":"FolderObjectId","dataType":"string"},{"name":"FolderDisplayName","dataType":"string"},{"name":"FolderAccessRequests","dataType":"string"},{"name":"DashboardName","dataType":"string"},{"name":"DashboardId","dataType":"string"},{"name":"Datasets","dataType":"string"},{"name":"DataConnectivityMode","dataType":"string"},{"name":"LastRefreshTime","dataType":"string"},{"name":"ImportId","dataType":"string"},{"name":"ImportSource","dataType":"string"},{"name":"ImportType","dataType":"string"},{"name":"ImportDisplayName","dataType":"string"},{"name":"SwitchState","dataType":"string"},{"name":"PackageId","dataType":"string"},{"name":"GatewayId","dataType":"string"},{"name":"RefreshType","dataType":"string"},{"name":"OldSensitivityLabelId","dataType":"string"},{"name":"ActionSource","dataType":"string"},{"name":"LabelEventType","dataType":"string"},{"name":"ActionSourceDetail","dataType":"string"},{"name":"ArtifactType","dataType":"string"},{"name":"SensitivityLabelEventData","dataType":"string"},{"name":"ItemId","dataType":"string"},{"name":"ItemType","dataType":"string"},{"name":"CapacityUsers","dataType":"string"},{"name":"CapacityState","dataType":"string"},{"name":"WorkspacesSemicolonDelimitedList","dataType":"string"},{"name":"EndPoint","dataType":"string"},{"name":"TileText","dataType":"string"},{"name":"GitIntegrationRequest","dataType":"string"},{"name":"GatewayClustersObjectIds","dataType":"string"},{"name":"GatewayType","dataType":"string"},{"name":"GatewayStatus","dataType":"string"}]}]}